services:
  - type: web
    name: app-votacao
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn votacao.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: votacao.settings
      - key: PYTHON_VERSION
        value: 3.11


